import React from 'react';
const data = {
    allData : [
        {
            banner:'https://cdn.ican.pl/minimized/v2/M1024xM2048xA/reader-files/book/Py9f6gXv7/1/cover.jpg',
            icon:'entities2.svg',
            title:'Client contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'123',
            lastUpdate:'2',
        },
        {
            banner:'https://i.dobrzemieszkaj.pl/i/48/54/01/r3/1920/industrialne-biuro-zobaczcie-wnetrza-zaprojektowane-dla-programistow.jpg',
            icon:'publications.svg',
            title:'Supplier contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'22',
            lastUpdate:'4',
        },
        {
            banner:'https://cdn.ican.pl/minimized/v2/M1024xM2048xA/reader-files/book/Py9f6gXv7/1/cover.jpg',
            icon:'entities2.svg',
            title:'Client contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'123',
            lastUpdate:'2',
        },
        {
            banner:'https://i.dobrzemieszkaj.pl/i/48/54/01/r3/1920/industrialne-biuro-zobaczcie-wnetrza-zaprojektowane-dla-programistow.jpg',
            icon:'publications.svg',
            title:'Supplier contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'22',
            lastUpdate:'4',
        },
        {
            banner:'https://cdn.ican.pl/minimized/v2/M1024xM2048xA/reader-files/book/Py9f6gXv7/1/cover.jpg',
            icon:'entities2.svg',
            title:'Client contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'123',
            lastUpdate:'2',
        },
        {
            banner:'https://i.dobrzemieszkaj.pl/i/48/54/01/r3/1920/industrialne-biuro-zobaczcie-wnetrza-zaprojektowane-dla-programistow.jpg',
            icon:'publications.svg',
            title:'Supplier contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'22',
            lastUpdate:'4',
        },
        {
            banner:'https://i.dobrzemieszkaj.pl/i/48/54/01/r3/1920/industrialne-biuro-zobaczcie-wnetrza-zaprojektowane-dla-programistow.jpg',
            icon:'entities2.svg',
            title:'Supplier contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'22',
            lastUpdate:'4',
        },
        {
            banner:'https://i.dobrzemieszkaj.pl/i/48/54/01/r3/1920/industrialne-biuro-zobaczcie-wnetrza-zaprojektowane-dla-programistow.jpg',
            icon:'publications.svg',
            title:'Supplier contract',
            smallIcon:'comments.svg',
            smallIconType:'Contract',
            smallIcon2:'people.svg',
            userCount:'22',
            lastUpdate:'4',
        }
    ]

}   
export default data;